# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/rocky8"
  config.vm.box_download_insecure = true

  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.1.2" 
  
  # Configura o provider como VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end
end

#config.vm.synced_folder ".", "/vagrant", type: "nfs"
#config.vm.provision "shell", path: "provision.sh"
#config.vm.network "forwarded_port", guest: 2222, host: 2222
