---
- name: Configurar servidor de aplicação java
  hosts: app01
  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbpassword: "devops"

  tasks:
    - name: Configurar o host do lab ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01
    - name: Criar o usuário do app
      user: app
      comment: "Usuario de aplicação"
      uid: 500
    - name: Instalar o maven
      yum:
        name: maven
        state: latest
    - name: Instalar Java 1.8
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: Criar diretórios de aplicação do app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: Clonar repositório do código-fonte
      git:
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Configurar arquivo de propriedades para a camada de banco
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: Gerar pacote da aplicação
      command: mvn -f /opt/notes/pom.xml package
      become_user: app
    - name: Registrar versão atual do pacote
      shell:
        cmd: mvn -o -q -Dexec.executable=echo -Dexec.args='${project.version}'
        chdir: /opt/notes
      register: app_version
    - name: Configurar serviço do systemd
      template:
        src: etc/systemd/system/notes.service
        src: /etc/systemd/system/notes.service
        notify: reload daemon
    - name: Iniciar o serviço notes
      services:
        name: notes
        state: restarted

  roles:
    - configuracao-default-so

  handlers:
    - name: reload app
      systemd:
        state: restarted
        deamon_target: yes
        name: 'notes'
    - name: reload deamon
      systemd:
        deamon reexec: yes
