---
- name: Configurar servidor de banco de dados
  hosts: db01
  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "vagrant"
    - dbpassword: "devops" # não é uma boa prática o correto é consultar de um "cofre" em runtime
  tasks:
    - name: Configurar o host do lab ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql
