# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "generic/rocky8"
  config.vm.box_download_insecure = true

  config.vm.hostname = "db01"
  config.vm.network "private_network", ip: "192.168.1.4"
  config.vm.network "forwarded_port", guest: 3306, host: 3306  
  
  # Configura o provider como VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end
end


  #config.vm.synced_folder ".", "/vagrant", type: "nfs"
  #config.vm.provision "shell", path: "provision.sh"